export const ANNOTATIONS_PKG = '@k2mobility/dynamodb-data-mapper-annotations';

export const PROPERTY_DECORATORS = new Set(['attribute', 'hashKey', 'rangeKey', 'autoGeneratedHashKey', 'versionAttribute']);
export const SKIP_DECORATORS = new Set(['autoGeneratedHashKey', 'versionAttribute']);
export const CLASS_DECORATORS = new Set(['table', 'schema']);

export const TYPED_ARRAY_NAMES = new Set([
    'Uint8Array', 'Int8Array', 'Uint16Array', 'Int16Array',
    'Uint32Array', 'Int32Array', 'Float32Array', 'Float64Array',
    'Uint8ClampedArray', 'ArrayBuffer', 'DataView',
]);
