import * as path from 'path';
import { Project, SourceFile } from 'ts-morph';
import { ANNOTATIONS_PKG } from './constants';
import { ClassRegistryImpl } from './classRegistry';
import { FileRewriter } from './fileRewriter';
import { TypeMapper } from './typeMapper';
import { FileChange, MigratorOptions, MigratorResult, UnresolvedField } from './types';

export type { FileChange, MigratorOptions, MigratorResult };

export class Migrator {
    private readonly options: MigratorOptions;

    constructor(options: MigratorOptions) {
        this.options = options;
    }

    scan(projectOverride?: Project): UnresolvedField[] {
        const { patterns, cwd } = this.options;
        const project = projectOverride ?? this.createProject(patterns, cwd);
        const sourceFiles = project.getSourceFiles();
        if (sourceFiles.length === 0) return [];
        const registry = new ClassRegistryImpl(sourceFiles);
        const fileRewriter = new FileRewriter(new TypeMapper(registry));
        return sourceFiles.flatMap(sf => fileRewriter.collectUnresolved(sf));
    }

    run(projectOverride?: Project): MigratorResult {
        const { patterns, cwd, dryRun, typeOverrides = {} } = this.options;
        const project = projectOverride ?? this.createProject(patterns, cwd);
        const sourceFiles = project.getSourceFiles();

        if (sourceFiles.length === 0) {
            return { changes: [], warnings: [] };
        }

        // Key by "className@filePath" — stable across AST mutations (compiler symbols are not).
        const registry = new ClassRegistryImpl(sourceFiles);
        const fileRewriter = new FileRewriter(new TypeMapper(registry, typeOverrides));

        const warnings: string[] = [];
        const changes: FileChange[] = [];

        this.rewritePropertyDecorators(sourceFiles, fileRewriter, warnings, changes, dryRun);
        this.injectMissingSchemas(registry, changes, dryRun);

        return { changes, warnings };
    }

    private createProject(patterns: string[], cwd: string): Project {
        const project = new Project({ compilerOptions: { strict: true, skipLibCheck: true } });
        project.addSourceFilesAtPaths(patterns.map(p => path.resolve(cwd, p)));
        return project;
    }

    private rewritePropertyDecorators(
        sourceFiles: SourceFile[],
        fileRewriter: FileRewriter,
        warnings: string[],
        changes: FileChange[],
        dryRun: boolean,
    ): void {
        for (const sf of sourceFiles) {
            const originalText = sf.getFullText();
            const fileWarnings = fileRewriter.rewrite(sf);
            warnings.push(...fileWarnings);
            const newText = sf.getFullText();
            if (newText !== originalText) {
                changes.push({ filePath: sf.getFilePath(), originalText, newText });
                if (!dryRun) sf.saveSync();
            }
        }
    }

    // Classes with only SKIP decorators (@autoGeneratedHashKey, @versionAttribute) are typically
    // @table root classes — registered for Document lookup but don't need @schema() injection.
    private injectMissingSchemas(
        registry: ClassRegistryImpl,
        changes: FileChange[],
        dryRun: boolean,
    ): void {
        const injectedFiles = new Set<SourceFile>();

        for (const info of registry.entries()) {
            if (info.hasTableOrSchema) continue;
            const classDecl = info.classDecl;
            if (ClassRegistryImpl.hasDynamoDbClassDecorator(classDecl)) continue;
            if (!ClassRegistryImpl.hasNonSkipPropertyDecorator(classDecl)) continue;

            classDecl.addDecorator({ name: 'schema', arguments: [] });
            const sf = classDecl.getSourceFile();
            this.ensureSchemaImported(sf);
            injectedFiles.add(sf);
        }

        for (const sf of injectedFiles) {
            const existing = changes.find(c => c.filePath === sf.getFilePath());
            const newText = sf.getFullText();
            if (existing) {
                existing.newText = newText;
                if (!dryRun) sf.saveSync();
            } else {
                changes.push({ filePath: sf.getFilePath(), originalText: '', newText });
                if (!dryRun) sf.saveSync();
            }
        }
    }

    private ensureSchemaImported(sf: SourceFile): void {
        const existing = sf.getImportDeclaration(ANNOTATIONS_PKG);
        if (existing) {
            if (!existing.getNamedImports().some(i => i.getName() === 'schema')) {
                existing.addNamedImport('schema');
            }
        } else {
            sf.addImportDeclaration({ moduleSpecifier: ANNOTATIONS_PKG, namedImports: ['schema'] });
        }
    }
}
